version: "3"
services:
  web:
    container_name: butterfly_web
    build: ./webpage
    restart: always
    volumes:
      - ./webpage:/butterfly

  backend:
    container_name: butterfly_backend
    build: ./backend
    ports:
      - 8000:8000
    depends on: db

  db:
    container_name: butterfly_db
    image: sqlite
    restart: always

  nginx:
    container_name: butterfly_nginx
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    env_file:
      - ./nginx-certbot.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
      - ./user_conf.d:/etc/nginx/user_conf.d
    depends_on:
      - web

volumes:
  nginx_secrets:
